
services:
  gomoku:
    build:
      dockerfile_inline: |
        FROM swipl:10.1.5
        USER root
        RUN apt-get update
        RUN apt-get install -y npm
        WORKDIR /var/www/app
        COPY app/package.json app/package-lock.json ./
        RUN npm ci
        COPY app ./
        COPY bot ./bot
    entrypoint: [npm,run,dev]
    ports: [3000:3000]
    develop:
      watch:
        - action: sync
          path: bot
          target: /var/www/app/bot
        - action: sync
          path: app
          target: /var/www/app
