
S=src
O=obj
I=inc
T=bin

MODEFLAGS =
CXXFLAGS = $(MODEFLAGS)
CXXFLAGS += -Wextra -Werror -Wall -pedantic $(I:%=-I %/)
CXXFLAGS += -fdiagnostics-color=always
CXXFLAGS += -fconcepts-diagnostics-depth=4
MDKEY = $(CXX) $(MODEFLAGS)

NAME = gomoku

STD=-std=c++23
CXX=g++ $(STD)

LD = $(CXX)
LDFLAGS =
LDCMD = $(LD) -o $@ $^ $(LDFLAGS)

SRC = $S/main.cpp $S/Gomoku.cpp
